### ISSUE TITLE
Configuration persistence

### ISSUE THREAD

**Issue by micdenny** [bloomberg/amqpprox#58]
Does amqpprox support configuration persistence and save the configuration on file?

How it survives a server reboot or fail? Do you script the configuration as `amqpprox_ctl` commands and submit on each reboot?

Probably is connected to #57

**Comment by adamncasey** [comment]
> Does amqpprox support configuration persistence and save the configuration on file?

No, amqpprox only receives commands from amqpprox_ctl. Synchronising static file config & dynamic config commands can be awkward, this approach means amqpprox only needs to understand how to read config from one source.

 > Do you script the configuration as amqpprox_ctl commands and submit on each reboot?

Yeah - when the server comes up it's another application above `amqpprox` which actually starts `amqpprox` & submits the configuration commands. If amqpprox fails the parent application will also exit, which then kicks our process supervisor into gear & brings everything back up again as before.

Thanks again for your input - interested to hear how you get on with this down the line

**Comment by micdenny** [comment]
I was expecting something like this, but I've asked to be sure I didn't miss some part of amqpprox 😄 

I think I'm good with the reply and I'm going to close the issue because it's by-design.

Thank you very much.
