### ISSUE TITLE
What's the use of PAUSE a vhost?

### ISSUE THREAD

**Issue by bechampion** [bloomberg/amqpprox#66]
As far as i notice the clients start loosing HB frames until they disconnect , what i was able to replicate is PAUSING/UNPAUSING quick enough within the HB Interval configured on the clients (and hopefully loosing 1 of the 2 HB frames within the interval) will not disconnect the client.

I wonder what's the function of PAUSING ? also i tried PAUSING ->REMAPPING -> UNPAUSING , but still my client ends up going to the same rabbitmq server until i reconnect.

Thank you!

**Comment by adamncasey** [comment]
Hey @bechampion . It's a good question, and your observations around heartbeats align with what we see.

The aim of pausing is to support a stateful vhost migration from one broker to another. By pausing the vhost & forcing the clients to disconnect you can stabilise the state of the vhost, which makes the process of migrating to another broker possible / a lot simpler.

Once the vhost has been remapped you need to force disconnect the clients to ensure they're forwarded to the correct broker.

**Comment by adamncasey** [comment]
Sorry hit close with comment a bit early there - I updated the above comment - let me know if this helps

**Comment by bechampion** [comment]
It does help a lot ,  thank you so much.

**Comment by willhoy** [comment]
Marking closed
